# Generated by Django 2.2 on 2021-09-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0002_auto_20200421_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalcomment',
            options={'ordering': ('-created',)},
        ),
    ]
