# Generated by Django 2.2 on 2021-09-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0003_auto_20210908_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalcomment',
            options={'ordering': ('created',)},
        ),
    ]
