# Generated by Django 2.2 on 2021-09-02 19:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh', '0002_auto_20200421_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangladeshpost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='/static/images/postdefault.jpg', force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='images/', verbose_name=[300, 300]),
        ),
    ]
