# Generated by Django 2.2 on 2021-09-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh', '0003_auto_20210903_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangladeshpost',
            name='image',
            field=models.ImageField(default='/static/images/postdefault.jpg', upload_to='images/'),
        ),
    ]
